import { defineField, defineType } from 'sanity';
import { imageAltCaptionFields } from './objects';

export const caseStudy = defineType({
    name: 'caseStudy',
    title: 'Case Study',
    type: 'document',
    groups: [
        { name: 'content', title: 'Content', default: true },
        { name: 'media', title: 'Media' },
        { name: 'details', title: 'Details & proof' },
        { name: 'seo', title: 'SEO' },
    ],
    fields: [
        defineField({
            name: 'title',
            title: 'Title',
            type: 'string',
            group: 'content',
            validation: (rule) => rule.required(),
        }),
        defineField({
            name: 'slug',
            title: 'Slug',
            type: 'slug',
            group: 'content',
            options: { source: 'title', maxLength: 96 },
            validation: (rule) => rule.required(),
        }),
        defineField({
            name: 'category',
            title: 'Category label',
            type: 'string',
            group: 'content',
            description: 'Shown as the eyebrow tag on the case study page.',
        }),
        defineField({
            name: 'subtitle',
            title: 'Subtitle (H1)',
            type: 'string',
            group: 'content',
            validation: (rule) => rule.required(),
        }),
        defineField({
            name: 'description',
            title: 'Short description',
            type: 'text',
            rows: 3,
            group: 'content',
            validation: (rule) => rule.required(),
        }),
        defineField({
            name: 'coverImage',
            title: 'Cover image',
            type: 'image',
            group: 'media',
            options: { hotspot: true },
            fields: imageAltCaptionFields,
            validation: (rule) => rule.required(),
            description: 'Primary listing and detail image. Set hotspot/crop so replacements do not need frontend work.',
        }),
        defineField({
            name: 'logo',
            title: 'Logo',
            type: 'image',
            group: 'media',
            options: { hotspot: true },
            fields: [
                defineField({
                    name: 'alt',
                    title: 'Alt text',
                    type: 'string',
                    description: 'Example: PropertyMatch logo',
                }),
            ],
            description: 'Optional client or product logo. Mapped for the frontend; layout does not change until a page opts in.',
        }),
        defineField({
            name: 'featuredOnHomepage',
            title: 'Featured on homepage',
            type: 'boolean',
            group: 'content',
            description:
                'Candidate for the homepage showcase when the Homepage document list is empty. Hidden studies stay excluded in code.',
            initialValue: false,
        }),
        defineField({
            name: 'client',
            title: 'Client',
            type: 'string',
            group: 'content',
        }),
        defineField({
            name: 'location',
            title: 'Location',
            type: 'string',
            group: 'content',
        }),
        defineField({
            name: 'industry',
            title: 'Industry',
            type: 'string',
            group: 'content',
        }),
        defineField({
            name: 'challenge',
            title: 'Challenge',
            type: 'text',
            rows: 5,
            group: 'content',
            description: 'Optional short challenge summary. Leave blank rather than inventing one.',
        }),
        defineField({
            name: 'solution',
            title: 'Solution',
            type: 'text',
            rows: 5,
            group: 'content',
            description: 'Optional short solution summary. Leave blank rather than inventing one.',
        }),
        defineField({
            name: 'outcome',
            title: 'Outcome',
            type: 'text',
            rows: 5,
            group: 'content',
        }),
        defineField({
            name: 'author',
            title: 'Author',
            type: 'reference',
            to: [{ type: 'person' }],
            group: 'content',
            validation: (rule) => rule.required(),
        }),
        defineField({
            name: 'projectValue',
            title: 'Project value',
            type: 'string',
            group: 'details',
        }),
        defineField({
            name: 'projectPeriod',
            title: 'Project period',
            type: 'string',
            group: 'details',
        }),
        defineField({
            name: 'deliveryDuration',
            title: 'Delivery duration',
            type: 'string',
            group: 'details',
            description:
                'Optional. Only enter a duration you can stand behind for a real engagement (e.g. “6 weeks”). Leave blank if it is not factual.',
        }),
        defineField({
            name: 'deliveredBy',
            title: 'Delivered by',
            type: 'string',
            group: 'details',
        }),
        defineField({
            name: 'engagementNote',
            title: 'Engagement note',
            type: 'text',
            rows: 2,
            group: 'details',
        }),
        defineField({
            name: 'portfolioNote',
            title: 'Portfolio note',
            type: 'text',
            rows: 2,
            group: 'details',
        }),
        defineField({
            name: 'atAGlance',
            title: 'At a glance',
            type: 'array',
            of: [{ type: 'stat' }],
            group: 'details',
        }),
        defineField({
            name: 'engagement',
            title: 'Engagement facts',
            type: 'array',
            of: [{ type: 'labelValue' }],
            group: 'details',
        }),
        defineField({
            name: 'stats',
            title: 'Stats',
            type: 'array',
            of: [{ type: 'labelValue' }],
            group: 'details',
        }),
        defineField({
            name: 'testimonial',
            title: 'Client testimonial',
            type: 'testimonial',
            group: 'details',
        }),
        defineField({
            name: 'detailedContent',
            title: 'Detailed sections',
            type: 'array',
            of: [{ type: 'caseStudySection' }],
            group: 'details',
        }),
        defineField({
            name: 'gallery',
            title: 'Gallery / screenshots',
            type: 'array',
            of: [
                {
                    type: 'image',
                    options: { hotspot: true },
                    fields: imageAltCaptionFields,
                },
            ],
            group: 'media',
            description: 'Screenshots and supporting images. Alt and caption are mapped for the case-study page.',
        }),
        defineField({
            name: 'backgroundImages',
            title: 'Background / detail images',
            type: 'array',
            of: [
                {
                    type: 'image',
                    options: { hotspot: true },
                    fields: imageAltCaptionFields,
                },
            ],
            group: 'media',
        }),
        defineField({
            name: 'cta',
            title: 'Page CTA',
            type: 'cta',
            group: 'details',
        }),
        defineField({
            name: 'seo',
            title: 'SEO',
            type: 'seoFields',
            group: 'seo',
        }),
        // Legacy flat SEO fields
        defineField({
            name: 'seoTitle',
            title: 'SEO title (legacy)',
            type: 'string',
            group: 'seo',
            hidden: ({ document }) => Boolean(document?.seo),
            deprecated: { reason: 'Use the SEO object instead' },
        }),
        defineField({
            name: 'seoDescription',
            title: 'SEO description (legacy)',
            type: 'text',
            rows: 3,
            group: 'seo',
            hidden: ({ document }) => Boolean(document?.seo),
            deprecated: { reason: 'Use the SEO object instead' },
        }),
        defineField({
            name: 'focusKeyword',
            title: 'Focus keyword (legacy)',
            type: 'string',
            group: 'seo',
            hidden: ({ document }) => Boolean(document?.seo),
            deprecated: { reason: 'Use the SEO object instead' },
        }),
    ],
    preview: {
        select: {
            title: 'title',
            subtitle: 'category',
            media: 'coverImage',
        },
    },
});
