import { defineField, defineType } from 'sanity';

export const caseStudy = defineType({
    name: 'caseStudy',
    title: 'Case Study',
    type: 'document',
    groups: [
        { name: 'content', title: 'Content', default: true },
        { name: 'seo', title: 'SEO' },
    ],
    fields: [
        defineField({
            name: 'title',
            title: 'Title',
            type: 'string',
            group: 'content',
            validation: (rule) => rule.required(),
        }),
        defineField({
            name: 'slug',
            title: 'Slug',
            type: 'slug',
            group: 'content',
            options: { source: 'title', maxLength: 96 },
            validation: (rule) => rule.required(),
        }),
        defineField({
            name: 'category',
            title: 'Category label',
            type: 'string',
            group: 'content',
            description: 'Shown as the eyebrow tag on the case study page.',
        }),
        defineField({
            name: 'subtitle',
            title: 'Subtitle (H1)',
            type: 'string',
            group: 'content',
            validation: (rule) => rule.required(),
        }),
        defineField({
            name: 'description',
            title: 'Short description',
            type: 'text',
            rows: 3,
            group: 'content',
            validation: (rule) => rule.required(),
        }),
        defineField({
            name: 'coverImage',
            title: 'Cover image',
            type: 'image',
            group: 'content',
            options: { hotspot: true },
            validation: (rule) => rule.required(),
        }),
        defineField({
            name: 'client',
            title: 'Client',
            type: 'string',
            group: 'content',
        }),
        defineField({
            name: 'location',
            title: 'Location',
            type: 'string',
            group: 'content',
        }),
        defineField({
            name: 'industry',
            title: 'Industry',
            type: 'string',
            group: 'content',
        }),
        defineField({
            name: 'challenge',
            title: 'Challenge',
            type: 'text',
            rows: 5,
            group: 'content',
        }),
        defineField({
            name: 'solution',
            title: 'Solution',
            type: 'text',
            rows: 5,
            group: 'content',
        }),
        defineField({
            name: 'outcome',
            title: 'Outcome',
            type: 'text',
            rows: 5,
            group: 'content',
        }),
        defineField({
            name: 'seoTitle',
            title: 'SEO title',
            type: 'string',
            group: 'seo',
        }),
        defineField({
            name: 'seoDescription',
            title: 'SEO description',
            type: 'text',
            rows: 3,
            group: 'seo',
            validation: (rule) => rule.max(160),
        }),
        defineField({
            name: 'focusKeyword',
            title: 'Focus keyword',
            type: 'string',
            group: 'seo',
        }),
    ],
    preview: {
        select: {
            title: 'title',
            subtitle: 'category',
            media: 'coverImage',
        },
    },
});
