import { defineField, defineType } from 'sanity';

const PAGE_KEYS = [
    { title: 'Engagement models', value: 'engagement-models' },
    { title: 'Book a call', value: 'book-a-call' },
    { title: 'Portfolio', value: 'portfolio' },
    { title: 'Reviews', value: 'reviews' },
    { title: 'Security', value: 'security' },
    { title: 'Process', value: 'process' },
    { title: 'Careers', value: 'careers' },
    { title: 'About', value: 'about' },
    { title: 'Services index', value: 'services-index' },
    { title: 'Technologies index', value: 'technologies-index' },
    { title: 'Compare index', value: 'compare-index' },
    { title: 'Start a project', value: 'start-a-project' },
    { title: 'Engineering transformation', value: 'engineering-transformation' },
] as const;

function when(...keys: string[]) {
    return {
        hidden: ({ parent }: { parent?: { pageKey?: string } }) => !keys.includes(parent?.pageKey ?? ''),
    };
}

export const sitePage = defineType({
    name: 'sitePage',
    title: 'Site page',
    type: 'document',
    groups: [
        { name: 'content', title: 'Content', default: true },
        { name: 'details', title: 'Page details' },
        { name: 'seo', title: 'SEO' },
    ],
    fields: [
        defineField({
            name: 'pageKey',
            title: 'Page',
            type: 'string',
            group: 'content',
            options: { list: [...PAGE_KEYS] },
            validation: (rule) => rule.required(),
        }),
        defineField({
            name: 'title',
            title: 'Title',
            type: 'string',
            group: 'content',
        }),
        defineField({
            name: 'heroEyebrow',
            title: 'Hero eyebrow',
            type: 'string',
            group: 'content',
        }),
        defineField({
            name: 'heroHighlight',
            title: 'Hero highlight',
            type: 'string',
            group: 'content',
        }),
        defineField({
            name: 'heroSubtitle',
            title: 'Hero subtitle',
            type: 'text',
            rows: 3,
            group: 'content',
        }),
        defineField({
            name: 'intro',
            title: 'Intro',
            type: 'text',
            rows: 3,
            group: 'content',
        }),
        defineField({
            name: 'faqs',
            title: 'FAQs',
            type: 'array',
            of: [{ type: 'faqItem' }],
            group: 'content',
        }),
        defineField({
            name: 'relatedLinks',
            title: 'Related links',
            type: 'array',
            of: [{ type: 'link' }],
            group: 'content',
        }),
        defineField({
            name: 'cards',
            title: 'Cards',
            type: 'array',
            of: [{ type: 'titledText' }],
            group: 'details',
            ...when('about', 'careers', 'services-index'),
        }),
        defineField({
            name: 'models',
            title: 'Engagement models',
            type: 'array',
            of: [{ type: 'engagementModel' }],
            group: 'details',
            ...when('engagement-models'),
        }),
        defineField({
            name: 'comparisonHeaders',
            title: 'Comparison headers',
            type: 'array',
            of: [{ type: 'string' }],
            group: 'details',
            ...when('engagement-models'),
        }),
        defineField({
            name: 'comparisonRows',
            title: 'Comparison rows',
            type: 'array',
            of: [{ type: 'comparisonTableRow' }],
            group: 'details',
            ...when('engagement-models'),
        }),
        defineField({
            name: 'included',
            title: 'Included',
            type: 'array',
            of: [{ type: 'string' }],
            group: 'details',
            ...when('engagement-models'),
        }),
        defineField({
            name: 'notIncluded',
            title: 'Not included',
            type: 'array',
            of: [{ type: 'string' }],
            group: 'details',
            ...when('engagement-models'),
        }),
        defineField({
            name: 'selectorGuide',
            title: 'Selector guide',
            type: 'array',
            of: [{ type: 'titledText' }],
            group: 'details',
            ...when('engagement-models'),
        }),
        defineField({
            name: 'listSections',
            title: 'List sections',
            type: 'array',
            of: [{ type: 'titledList' }],
            group: 'details',
            description: 'Use keys: whoFor, whatWeCover, whatToPrepare, goodFit, notFit.',
            ...when('book-a-call'),
        }),
        defineField({
            name: 'projects',
            title: 'Projects',
            type: 'array',
            of: [{ type: 'portfolioProject' }],
            group: 'details',
            ...when('portfolio'),
        }),
        defineField({
            name: 'quotes',
            title: 'Quotes',
            type: 'array',
            of: [{ type: 'testimonial' }],
            group: 'details',
            ...when('reviews'),
        }),
        defineField({
            name: 'contentSections',
            title: 'Content sections',
            type: 'array',
            of: [{ type: 'richSection' }],
            group: 'details',
            ...when('security', 'about', 'engineering-transformation'),
        }),
        defineField({
            name: 'processSteps',
            title: 'Process steps',
            type: 'array',
            of: [{ type: 'processStepItem' }],
            group: 'details',
            ...when('process'),
        }),
        defineField({
            name: 'values',
            title: 'Values',
            type: 'array',
            of: [{ type: 'titledText' }],
            group: 'details',
            ...when('careers'),
        }),
        defineField({
            name: 'jobs',
            title: 'Jobs',
            type: 'array',
            of: [{ type: 'jobListing' }],
            group: 'details',
            ...when('careers'),
        }),
        defineField({
            name: 'sectionEyebrow',
            title: 'Section eyebrow',
            type: 'string',
            group: 'details',
            ...when('about', 'services-index', 'careers'),
        }),
        defineField({
            name: 'sectionTitle',
            title: 'Section title',
            type: 'string',
            group: 'details',
            ...when('about', 'services-index', 'careers'),
        }),
        defineField({
            name: 'sectionLede',
            title: 'Section lede',
            type: 'text',
            rows: 2,
            group: 'details',
            ...when('about', 'services-index', 'careers'),
        }),
        defineField({
            name: 'ctaTitle',
            title: 'CTA title',
            type: 'string',
            group: 'details',
        }),
        defineField({
            name: 'ctaLede',
            title: 'CTA lede',
            type: 'text',
            rows: 2,
            group: 'details',
        }),
        defineField({
            name: 'seo',
            title: 'SEO',
            type: 'seoFields',
            group: 'seo',
        }),
    ],
    preview: {
        select: { title: 'title', pageKey: 'pageKey' },
        prepare({ title, pageKey }) {
            const match = PAGE_KEYS.find((item) => item.value === pageKey);
            return {
                title: title || match?.title || 'Site page',
                subtitle: match?.title || pageKey,
            };
        },
    },
});
